motor_handler:
  ros__parameters:
    joint_names: ['elbow', 'wrist_pitch']
    baud_rate: 1000000
    protocol: 2
    wrist_pitch:
      port_name: "/dev/ttyUSB0"
      joint_type: "soft_joint"
      right:
        motor_id: 30
        action_id: 0
        movement_direction: 1
      left:
        motor_id: 31
        action_id: 1
        movement_direction: 1
    elbow:
      port_name: "/dev/ttyUSB0"
      joint_type: "soft_joint"
      right:
        motor_id: 30
        action_id: 0
        movement_direction: 1
      left:
        motor_id: 31
        action_id: 1
        movement_direction: 1
      