/shoulder/motor_handler:
  ros__parameters:
    joint_names: ['shoulder_yaw', 'shoulder_roll', 'shoulder_pitch']
    port_name: "/dev/serial/by-id/usb-FieldworkRobotics_GH2_Shoulder-RS485_D35ZDA8R-if00-port0"
    baud_rate: 1000000
    protocol: 2
    shoulder_yaw:
      joint_type: "soft_joint"
      min_joint_angle: -1.5708
      max_joint_angle: 1.5708
      motor_init_pos: 0.0
      right:
        motor_id: 1
        movement_direction: 1
        offset: 0.0
      left:
        motor_id: 2
        movement_direction: 1
        offset: 0.0
    shoulder_roll:
      joint_type: "soft_joint"
      min_joint_angle: -1.5708
      max_joint_angle: 1.5708
      motor_init_pos: 0.0
      right:
        motor_id: 3
        movement_direction: 1
        offset: 0.0
      left:
        motor_id: 4
        movement_direction: 1
        offset: 0.0
    shoulder_pitch:
      joint_type: "soft_joint"
      min_joint_angle: 0.0
      max_joint_angle: 1.5708
      motor_init_pos: 3.1416
      right:
        motor_id: 5
        movement_direction: 1
        offset: -3.1416
      left:
        motor_id: 6
        movement_direction: -1
        offset: -9.4248

/upperarm/motor_handler:
  ros__parameters:
    joint_names: ['upperarm_roll', 'elbow']
    port_name: "/dev/serial/by-id/usb-FieldworksRobotics_GH2_Upper-RS485_D35ZFRUI-if00-port0"
    baud_rate: 1000000
    protocol: 2
    upperarm_roll:
      joint_type: "soft_joint"
      min_joint_angle: -3.0
      max_joint_angle: 3.0
      motor_init_pos: 0.0
      right:
        motor_id: 7
        movement_direction: -1
        offset: 3.1416
      left:
        motor_id: 8
        movement_direction: -1
        offset: -3.1416
    elbow:
      joint_type: "soft_joint"
      min_joint_angle: -0.1
      max_joint_angle: 2.2
      motor_init_pos: 3.1416
      right:
        motor_id: 10
        movement_direction: -1
        offset: -9.4248
      left:
        motor_id: 9
        movement_direction: 1
        offset: -2.1916
      

/lowerarm/motor_handler:
  ros__parameters:
    joint_names: ['forearm_roll', 'wrist_pitch']
    port_name: "/dev/serial/by-id/usb-FieldworkRobotics_GH2_Lower-RS485_D35NR2H3-if00-port0"
    baud_rate: 1000000
    protocol: 2
    wrist_pitch:
      joint_type: "soft_joint"
      min_joint_angle: -1.5708
      max_joint_angle: 1.5708
      motor_init_pos: 0.0
      right:
        motor_id: 13
        movement_direction: -1
        offset: 0.0
      left:
        motor_id: 12
        movement_direction: 1
        offset: 0.0
    forearm_roll:
      joint_type: "motor_joint"
      min_joint_angle: -1.5708
      max_joint_angle: 1.5708
      motor_init_pos: 0.0
      motor_id: 11
      movement_direction: -1
      offset: -3.1416
      